/*/**:
  ros__parameters:

    input:
      image_topics:
        - /drivers/zed_camera/front_center/left/image_rect_color
        - /drivers/zed_camera/front_left/left/image_rect_color
        - /drivers/zed_camera/front_right/left/image_rect_color
      /drivers/zed_camera/front_left/left/image_rect_color:
        camera_info_topic: /drivers/zed_camera/front_left/left/camera_info
      /drivers/zed_camera/front_center/left/image_rect_color:
        camera_info_topic: /drivers/zed_camera/front_center/left/camera_info
      /drivers/zed_camera/front_right/left/image_rect_color:
        camera_info_topic: /drivers/zed_camera/front_right/left/camera_info

    output:
      projection:
        planar:
          enabled: true
          image_topic: /image_reprojection/planar/image
          camera_info_topic: /image_reprojection/planar/camera_info
          optical_frame_id: front_center_left_camera_optical_frame
          width: 2560
          height: 720
          depth: 10.0
          fov_x: 120.0
          blend_factor: 0.0
        equirectangular:
          enabled: true
          image_topic: /image_reprojection/equirectangular/image
          camera_info_topic: /image_reprojection/equirectangular/camera_info
          optical_frame_id: front_center_left_camera_optical_frame
          width: 2560
          height: 720
          radius: 10.0
          fov_x: 120.0
          blend_factor: 0.0

    params:
      recompute_every_frame: false
      sync_queue_size: 10 # Synchronisation queue length for ApproximateTime
      transform_timeout: 0.05 # TF lookup timeout in seconds
      frame_timeout: 1.0 # Maximum age (s) to keep partial frame data when waiting for other cameras
      frame_time_tolerance: 0.01 # Maximum time difference (s) between cameras to assemble a joint frame
