include:
  - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml

variables:
  PLATFORM: amd64,arm64
  TARGET: dev,run
  BASE_IMAGE: rwthika/ros2-cuda:jazzy-ros-base
  COMMAND: ros2 launch image_reprojection image_reprojection_launch.py
  RMW_IMPLEMENTATION: rmw_zenoh_cpp
  ENABLE_SLIM: false
