services:

  zenoh-router:
    extends:
      file: ./docker-compose-essentials/docker-compose.template.yml
      service: zenoh-router
    ports:
      - 7447:7447

  lichtblick:
    extends:
      file: ./docker-compose-essentials/docker-compose.template.yml
      service: lichtblick

  foxglove-bridge:
    extends:
      file: ./docker-compose-essentials/docker-compose.template.yml
      service: foxglove-bridge
