apiVersion: v2
name: image-reprojection
version: 1.1.1
appVersion: 1.1.1
description: Planar and Equirectangular Image Reprojection/Stitching for ROS 2 and GStreamer
dependencies:
  - repository: oci://ghcr.io/openads-project/openads-helm
    name: openadservice
    version: 1.0.0
